title: Uzodinma
logo: ! [Uzodinma Okafor] (https://github.com/uzodinma-okafor/uzodinma-okafor.github.io/blob/main/assets/images/20141206_154458.jpg)
show_downloads: True
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
